---
- name: install required packages
  yum:
    name: "{{ item }} "
  with_items:
  - java-1.8.0-openjdk
  - tomcat
  - tomcat-webapps
  - tomcat-admin-webapps

- name: copy user.xml
  template:
    src: tomcat-users.xml
    dest: /usr/share/tomcat/conf
    
- name: download artifacts
  get_url: 
    url: http://18.117.9.166:8081/nexus/service/local/repositories/jaga/content/java1/api/15/api-15.war
    dest: /usr/share/tomcat
    url_username: jaga
    url_password: jaga

- name: retsart tomcat
  systemd:
    name: tomcat
    state: restarted

# tasks file for tomcat
